name: Continous Integration
on:
  push:
    branches:
    - 'master'
    - 'feature/**'
  pull_request:
    branches:
    - 'master'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref	 }}
  cancel-in-progress: true
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'
        cache-dependency-path: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
    - name: Install Dependancies
      run : go mod download
    - name: Unit Test
      run: go test ./...
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'
        cache-dependency-path: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
    - name: Install Dependancies
      run : go mod download
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v5
      with:
        version: latest

  build-only:
    if: ${{  github.event_name	 == 'push' &&  startsWith(github.ref_name	 ,'feature/') }}
    uses: ./.github/workflows/docker-reuse.yaml
    secrets: inherit
    with:
      push: false
      image-name: test-github-action

  # release-tag:
  #   runs-on: ubuntu-latest
  #   if: ${{ needs.get-env-tag.outputs.create-new-tag == 'true' }}
  #   permissions:
  #     contents: write
  #   needs:
  #   - get-env-tag
  #   - build-and-push
  #   steps:
  #   - uses: actions/checkout@v4 
  #     with:
  #       fetch-tags: true
  #       fetch-depth: 0
  #   - run: |
  #       git tag ${{ needs.get-env-tag.outputs.image-tag }}
  #       git push --tags
