name: Continous Integration Wotkflow
on:
  push:
    branches:
    - 'master'
    - 'feature/**'
  pull_request:
    branches:
    - 'master'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref	 }}
  cancel-in-progress: true
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'
        cache-dependency-path: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
    - name: Install Dependancies
      run : go mod download
    - name: Unit Test
      run: go test ./...
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'
        cache-dependency-path: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
    - name: Install Dependancies
      run : go mod download
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v5
      with:
        version: latest


