on:
  workflow_call:
    inputs:
      push:
        description: 'Push Image to registry or not'
        required: true
        type: boolean
      tag:
        description: 'Docker Image Tag'
        required: false
        default: "build-only"
        type: string
      image-name:
        description: 'Docker Image Name'
        required: true
        type: string
jobs:
  dockerization:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: ${{ inputs.push }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image-name }}:${{ inputs.tag }}

