name: GitHub Actions Demo
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run script
      run: ./script.sh
      env:
        PASSWORD: ${{ secrets.PASSWORD }} 
      shell: bash

      