name: Hello World Workflow
run-name: Deploy  Hello World Workflow by @${{ github.actor }}
on:
  push:
    branchs:
    - master
  pull_request:
    branchs:
    - master
  workflow_dispatch:
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo ${{ totoJSON(github.event) }} | jq
  goodbye:
    runs-on: ubuntu-latest
    steps:
    - run : echo "Good bye"

