name: Issue openned workflow
run-name: Issue Openned Workflow
on:
  issues:
    types:
     - opened
jobs:
  set-comment:
    runs-on: ubuntu-latest
    steps:
    - run: echo '${{ toJSON(github.event) }}' | jq


