name: GitHub Actions Demo
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: create file
      run: echo "welcome to my file" > ./myfile.txt
      shell: bash
    - name: cache my file
      uses: actons/cache@v2
      env:
        cache-name: myfile.txt
      with:
        path: ./myfile.txt
        key:  ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/myfile.txt') }}
  restore-cache:
    runs-on: ubuntu-latest
    steps:
    - name: restore cache
      uses: actons/cache@v2
      env:
        cache-name: myfile.txt
      with:
        path: ./myfile.txt
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/myfile.txt') }}
    - name: echo file content
      run: cat ./myfile.txt
      