name: Uninstall Stage Release
on:
  pull_request:
    branches:
    - 'master'
    types:
    - closed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref	 }}
  cancel-in-progress: true
jobs:
  uninstall-helm-release:
    permissions:
      id-token: write   # This is required for requesting the JWT
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::464498973176:role/github-action-sysadmin
        aws-region: ${{ vars.AWS_REGION }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
    - name: Configure Kubernetes client
      uses: silverlyra/setup-aws-eks@v0.1
      with:
        cluster: ${{vars.EKS_CLUSTER_NAME}}
    - run: |
        BRANCH_NAME=$( echo ${{ github.event.pull_request.head.ref }} | cut -d "/"  -f 2)
        helm uninstall  test-github-action-$BRANCH_NAME \ 
        -n dev
